baseURL = 'https://godot-jp.github.io/'
languageCode = 'ja-jp'
title = 'Godot Japan User Community'
theme = 'godot-jp'
disableKinds = ['taxonomy', 'term']
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1