baseURL = 'https://godot-jp.github.io/'
languageCode = 'ja-jp'
title = 'Godot Japan User Community'
theme = 'GodotJP-2023'
enableGitInfo = true
ignoreLogs = ['error-remote-getjson']

[pramas]
dafaultNoimage = "/images/m_e_other_501.png"
imageQuality = 75

[mediaTypes]
  [mediaTypes.'text/json']
    suffixes = ['json']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      block = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1