name = "Godot JP"
license = "MIT"
licenselink = "https://github.com/godot-jp/godot-jp/blob/main/LICENSE"
description = ""
homepage = "http://godot-jp.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Saitos"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
